{1}{}{PID_PURPLE_ROBE@Сшейте из старых кусков ткани один большой мешок, а потом добавьте к нему капюшон и рукава. Покрасить это дело соком из лепестков цветов - и вы уже похожи на хаболога!@@SK_OUTDOORSMAN 40@PID_RAGS 6&PID_POCKET_LINT 2&PID_BROC_FLOWER 3&PID_BOOZE 1@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_PURPLE_ROBE 1@exp 150 }
{2}{}{PID_LEATHER_JACKET@Сшейте куртку из шкурок, а затем замочите в красящем растворе.@@SK_OUTDOORSMAN 30@PID_GECKO_PELT 4&PID_POCKET_LINT 1&PID_CHEMICALS 1@PID_COMBAT_KNIFE 1|PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_SHIV 1@PID_LEATHER_JACKET 1@exp 175 }
{3}{}{PID_LEATHER_ARMOR@Шкуры брамина, сшитые в несколько слоёв, позволят чувствовать себя защищённей.@@SK_OUTDOORSMAN 60@PID_BRAHMIN_SKIN 2&PID_POCKET_LINT 1&PID_ROPE 1@PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_COMBAT_KNIFE 1@PID_LEATHER_ARMOR 1@exp 150 }
{4}{}{PID_LEATHER_ARMOR_MK_II@Укрепите броню несколькими слоями кожи и обработайте её химикатами для улучшения защитных свойств.@SK_OUTDOORSMAN 30@SK_OUTDOORSMAN 70@PID_LEATHER_ARMOR 1&PID_BRAHMIN_SKIN 1&PID_CHEMICALS 1@PID_COMBAT_KNIFE 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_LEATHER_ARMOR_MK_II 1@exp 100 }
{5}{}{PID_CURED_LEATHER_ARMOR@Если на горизонте показались проблемы, то лучше забыть про стиль и укрепить свою старую добрую куртку ещё десятком слоёв кожи.@SK_OUTDOORSMAN 50@SK_OUTDOORSMAN 70@PID_LEATHER_JACKET 1&PID_BRAHMIN_SKIN 2&PID_GOLDEN_GECKO_PELT 2&PID_POCKET_LINT 1@PID_SHIV 1|PID_COMBAT_KNIFE 1@PID_CURED_LEATHER_ARMOR 1@exp 200 }
{6}{}{PID_METAL_ARMOR@Боитесь ножей из-за угла и когтей гекко? С вашей новой металлической бронёй они будут для вас не более, чем царапинами. Для производства необходим верстак.@SK_REPAIR 40@SK_REPAIR 80@PID_METAL_TRASH 4&PID_PUMP_PARTS 1&PID_LEATHER_ARMOR 1&PID_WELDING 1@PID_SUPER_TOOL_KIT 1@PID_METAL_ARMOR 1@exp 400 script fix_boy@fix_AnyStuff}
{7}{}{PID_METAL_ARMOR_MK_II@Укрепите слабые места на броне, а затем обработайте напильником и отполируйте до блеска для лучше защиты от лазерного оружия. Для производства необходим верстак.@SK_REPAIR 60@SK_REPAIR 100@PID_METAL_ARMOR 1&PID_METAL_TRASH 2&PID_WELDING 1@PID_SUPER_TOOL_KIT 1&PID_MOUSE_SKIN 1@PID_METAL_ARMOR_MK_II 1@exp 350 script fix_boy@fix_AnyStuff}
{8}{}{PID_TESLA_ARMOR@Установите на свою металлическую броню катушки Тесла, чтобы они рассеивали заряды энергооружия. И не забудьте про шапочку из фольги!@SK_REPAIR 50&SK_SCIENCE 50@SK_REPAIR 130&SK_SCIENCE 150@PID_METAL_ARMOR_MK_II 1&PID_METAL_TRASH 2&PID_PUMP_PARTS 4&PID_V15_COMPUTER_PART 3&PID_MICRO_FUSION_CELL 50@PID_SUPER_TOOL_KIT 1&PID_BIG_BOOK_OF_SCIENCE 1@PID_TESLA_ARMOR 1@exp 450 }
{9}{}{PID_HARDENED_POWER_ARMOR@Эта заводская сборка ну просто никуда не годится. Броню можно перекалить и местами приварить дополнительную защиту. Главное - сумейте её потом собрать обратно.@SK_REPAIR 120@SK_SCIENCE 80&SK_REPAIR 150&ST_STRENGTH 8@PID_POWERED_ARMOR 1&PID_BOTTLE_FULL 10&PID_FIREWOOD 5&PID_WELDING 3&PID_METAL_TRASH 2@PID_SLEDGEHAMMER 1&PID_TECHNICAL_MANUAL 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1&PID_SUPER_TOOL_KIT 1@PID_HARDENED_POWER_ARMOR 1@exp 500 }
{100}{}{PID_SHOTGUN_SHELLS@Надо обладать недюжиной силой воли для того, чтобы пустить на пыжи такой журнал, как "Кошачья лапка".@SK_SCIENCE 80@SK_SCIENCE 90&SK_SMALL_GUNS 50&SK_REPAIR 80@PID_GUNPOWDER 2&PID_CATS_PAW 1&PID_REAL_BOTTLE_CAPS 40&PID_PUMP_PARTS 2@PID_SUPER_TOOL_KIT 1@PID_SHOTGUN_SHELLS 40@exp 100 }
{101}{}{PID_10MM_JHP@Зафиксируйте патрон на верстаке, стараясь не смять гильзу. Затем обрежьте кончики пуль, высверлите часть сердечника и загните края латунной оболочки внутрь, сделав в ней небольшие надрезы. Теперь пуля будет разрываться от удара о цель.@SK_REPAIR 30@SK_REPAIR 50@PID_10MM_AP 20@@PID_10MM_JHP 20@exp 50 script fix_boy@fix_AnyStuff}
{102}{}{PID_5MM_JHP@Зафиксируйте патрон на верстаке, стараясь не смять гильзу. Затем обрежьте кончики пуль, высверлите часть сердечника и загните края латунной оболочки внутрь, сделав в ней небольшие надрезы. Теперь пуля будет разрываться от удара о цель.@SK_REPAIR 30@SK_REPAIR 50@PID_5MM_AP 20@@PID_5MM_JHP 20@exp 50 script fix_boy@fix_AnyStuff}
{103}{}{PID_44_MAGNUM_JHP@Зафиксируйте патрон на верстаке, стараясь не смять гильзу. Затем обрежьте кончики пуль, высверлите небольшое углубление в сердцевине и загните края латунной оболочки внутрь, сделав в ней небольшие надрезы. Теперь пуля будет разрываться от удара о цель.@SK_REPAIR 30@SK_REPAIR 50@PID_44_FMJ_MAGNUM 20@@PID_44_MAGNUM_JHP 20@exp 50 script fix_boy@fix_AnyStuff}
{104}{}{PID_10MM_JHP@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны 10 мм, полуоболоченные".@@SK_SMALL_GUNS 50&SK_SCIENCE 50&SK_REPAIR 50@PID_GUNPOWDER 1&PID_METAL_TRASH 2@@PID_10MM_JHP 20@exp 100 script fix_boy@fix_AnyRounds}
{105}{}{PID_10MM_AP@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны 10 мм, бронебойные".@@SK_SMALL_GUNS 50&SK_SCIENCE 50&SK_REPAIR 50@PID_GUNPOWDER 1&PID_METAL_TRASH 1&PID_STEEL 1@@PID_10MM_AP 20@exp 150 script fix_boy@fix_AnyRounds}
{106}{}{PID_44_MAGNUM_JHP@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны калибра .44".@@SK_SMALL_GUNS 50&SK_SCIENCE 50&SK_REPAIR 50@PID_GUNPOWDER 1&PID_METAL_TRASH 2@@PID_44_MAGNUM_JHP 20@exp 100 script fix_boy@fix_AnyRounds}
{107}{}{PID_44_FMJ_MAGNUM@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны калибра .44, цельнометаллические".@@SK_SMALL_GUNS 50&SK_SCIENCE 50&SK_REPAIR 50@PID_GUNPOWDER 1&PID_METAL_TRASH 2@@PID_44_FMJ_MAGNUM 20@exp 100 script fix_boy@fix_AnyRounds}
{108}{}{PID_14MM_AP@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны 14мм".@@SK_SMALL_GUNS 50&SK_SCIENCE 50&SK_REPAIR 50@PID_GUNPOWDER 1&PID_METAL_TRASH 1&PID_STEEL 1@@PID_14MM_AP 20@exp 100 script fix_boy@fix_AnyRounds}
{109}{}{PID_223_FMJ@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны .223, цельнометаллические".@@SK_SMALL_GUNS 50&SK_SCIENCE 50&SK_REPAIR 50@PID_GUNPOWDER 1&PID_METAL_TRASH 2@@PID_223_FMJ 20@exp 100 script fix_boy@fix_AnyRounds}
{110}{}{PID_5MM_JHP@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны 5 мм, полуоболоченные".@@SK_SMALL_GUNS 50&SK_SCIENCE 50&SK_REPAIR 50@PID_GUNPOWDER 1&PID_METAL_TRASH 2@@PID_5MM_JHP 20@exp 100 script fix_boy@fix_AnyRounds}
{111}{}{PID_5MM_AP@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны 5 мм, бронебойные".@@SK_SMALL_GUNS 50&SK_SCIENCE 50&SK_REPAIR 50@PID_GUNPOWDER 1&PID_METAL_TRASH 1&PID_STEEL 1@@PID_5MM_AP 20@exp 100 script fix_boy@fix_AnyRounds}
{112}{}{PID_45_CALIBER_AMMO@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны калибра 0.45".@@SK_SMALL_GUNS 50&SK_SCIENCE 50&SK_REPAIR 50@PID_GUNPOWDER 1&PID_METAL_TRASH 2@@PID_45_CALIBER_AMMO 20@exp 100 script fix_boy@fix_AnyRounds}
{113}{}{PID_7_62MM_AMMO@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны калибра 7,62, цельнометаллические".@@SK_SMALL_GUNS 50&SK_SCIENCE 50&SK_REPAIR 50@PID_GUNPOWDER 1&PID_METAL_TRASH 2@@PID_7_62MM_AMMO 20@exp 100 script fix_boy@fix_AnyRounds}
{114}{}{PID_700_NITRO_EXPRESS@Понадобятся некоторые познания в электронике и баллистике для того, чтобы запрограммировать станок на производство этих необычных патронов.@@SK_SMALL_GUNS 80&SK_SCIENCE 80&SK_REPAIR 80@PID_GUNPOWDER 1&PID_METAL_TRASH 1@@PID_700_NITRO_EXPRESS 1@exp 150 script fix_boy@fix_NitroExpressRounds}
{115}{}{PID_EMP_ROCKET@На большой дистанции ЕМП-граната малоэффективна. Куда удобнее воспользоваться гранатометом, а подходящий снаряд вы легко изготовите "на коленке", если в рюкзаке найдутся соответствующие материалы.@@SK_SCIENCE 150&SK_REPAIR 100@PID_EXPLOSIVE_ROCKET 1&PID_PULSE_GRENADE 1&PID_V15_COMPUTER_PART 3@PID_MULTI_TOOL 1&PID_DEANS_ELECTRONICS 1@PID_EMP_ROCKET 1@exp 300 script fix_boy@fix_EmpRocket}
{200}{}{PID_MOLOTOV_COCKTAIL@Пойло, смешанное со смолянистым соком цветков, будет замечательно гореть и прилипать к противнику.@SK_SCIENCE 20@SK_SCIENCE 30&SK_OUTDOORSMAN 30@PID_ROT_GUT 1&PID_RAGS 1&PID_BROC_FLOWER 1@@PID_MOLOTOV_COCKTAIL 1@exp 50 }
{201}{}{PID_MOLOTOV_COCKTAIL@Нет огнемёта? Не беда, всегда можно найти способ доставить пламя до противника.@SK_SCIENCE 20@SK_SCIENCE 30&SK_REPAIR 30@PID_BOTTLE_GLASS 1&PID_RAGS 1&PID_FLAMETHROWER_FUEL 1@@PID_MOLOTOV_COCKTAIL 1@exp 50 }
{202}{}{PID_FLAMETHROWER_FUEL@Найдите в мусоре побольше пенопласта, растворяйте в ацетоне, пока эта смесь не станет густой. Дозаправьте баллон с топливом.@SK_SCIENCE 30@SK_SCIENCE 50&SK_REPAIR 60@PID_FLAMETHROWER_FUEL 1&PID_CHEMICALS 1&PID_PUMP_PARTS 1@@PID_FLAMETHROWER_FUEL 10@exp 50 }
{203}{}{PID_FLAMETHROWER_FUEL@Найдите в мусоре побольше пенопласта, растворяйте в ацетоне, пока эта смесь не станет густой. Заместите этой смесью газ в одном из баллонов сварки.@SK_SCIENCE 30@SK_SCIENCE 50&SK_REPAIR 60@PID_WELDING 1&PID_CHEMICALS 2&PID_PUMP_PARTS 2@PID_MULTI_TOOL 1@PID_FLAMETHROWER_FUEL 30@exp 100 }
{204}{}{PID_FLAMETHROWEF_FUEL_MKII@Немного алюминиевой пудры, натёртой собственными руками, повысит температуру горения топлива. Не рекомендуется использовать его со стандартными моделями огнемётов во избежание забивания сопла.@SK_REPAIR 50&SK_SCIENCE 50@SK_SCIENCE 60&SK_REPAIR 80@PID_FLAMETHROWER_FUEL 5&PID_METAL_TRASH 1@PID_MULTI_TOOL 1@PID_FLAMETHROWER_FUEL_MK_II 5@exp 100 }
{300}{}{PID_SCOPED_HUNTING_RIFLE@Для простенького прицела сойдут и линзы из чьих-нибудь очков, главное - чётко следовать инструкциям.@SK_SMALL_GUNS 50@SK_REPAIR 60&SK_SMALL_GUNS 60&SK_SCIENCE 30@PID_HUNTING_RIFLE 1&PID_SPECTACLES 1&PID_PUMP_PARTS 1@PID_GUNS_AND_BULLETS 1&PID_MULTI_TOOL 1@PID_SCOPED_HUNTING_RIFLE 1@exp 120 }
{301}{}{PID_ASSAULT_RIFLE_EXT_MAG@Изготовьте новый магазин и найдите в мусоре для него пружину помощнее.@SK_SMALL_GUNS 50@SK_REPAIR 70@PID_ASSAULT_RIFLE 1&PID_PUMP_PARTS 1@PID_SUPER_TOOL_KIT 1@PID_ASSAULT_RIFLE_EXT_MAG 1@exp 120 }
{302}{}{PID_SHOTGUN@Найдите две трубы более-менее подходящего диаметра, изготовьте к ним приклад и простенький спусковой механизм.@SK_SMALL_GUNS 50@SK_SMALL_GUNS 50&SK_REPAIR 40@PID_SHOTGUN_SHELLS 2&PID_TUBE 2&PID_FIREWOOD 1&PID_PUMP_PARTS 2@PID_MULTI_TOOL 1@PID_SHOTGUN 1@exp 150 }
{303}{}{PID_SAWED_OFF_SHOTGUN@Укорачивание ствола на десяток дюймов позволит комфортно прятать дробовик под одеждой, чтобы удивлять противника в самый неподходящий момент.@SK_REPAIR 40@SK_REPAIR 60@PID_SHOTGUN 1@PID_MULTI_TOOL 1@PID_SAWED_OFF_SHOTGUN 1@exp 100 }
{304}{}{PID_DESERT_EAGLE_EXT_MAG@С переделкой магазина придётся помучиться, но она сэкономит несколько драгоценных секунд в бою.@SK_REPAIR 60@SK_REPAIR 70@PID_DESERT_EAGLE 1&PID_PUMP_PARTS 1@PID_SUPER_TOOL_KIT 1@PID_DESERT_EAGLE_EXT_MAG 1@exp 80 }
{305}{}{PID_SPRINGER_RIFLE@Замените ствол на своём самопале для увеличения точности.@@SK_REPAIR 30&SK_SMALL_GUNS 50@PID_ZIP_GUN 1&PID_TUBE 1&PID_PUMP_PARTS 1@PID_MULTI_TOOL 1@PID_SPRINGER_RIFLE 1@exp 100 }
{306}{}{PID_ZIP_GUN@Прочно примотайте трубу проволокой к рукояти. Отнеситесь к этому серьёзно, иначе ваше оружие самоуничтожится после первого же выстрела.@@SK_REPAIR 20@PID_PUMP_PARTS 1&PID_FIREWOOD 1&PID_10MM_JHP 1@@PID_ZIP_GUN 1@exp 75 }
{307}{}{PID_FN_FAL_HPFA@Пускай отдача будет ломать вам плечо, но это улучшение того стоит.@SK_REPAIR 80@SK_SMALL_GUNS 80&SK_REPAIR 120@PID_FN_FAL 1&PID_METAL_TRASH 1&PID_PUMP_PARTS 1@PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1@PID_FN_FAL_HPFA 1@exp 150 }
{308}{}{PID_MAUSER_SMG@В одном из номеров журнала "Пушки и пули" была опубликована схема автоматического Маузера М712 калибра 7,62. Изучив её, вы поняли, что 9мм Маузер можно было бы переделать подобным образом. Для производства необходим верстак.@SK_SMALL_GUNS 50@SK_REPAIR 80@PID_9MM_MAUSER 1&PID_METAL_TRASH 1&PID_PUMP_PARTS 1@PID_MULTI_TOOL 1&PID_GUNS_AND_BULLETS 1@PID_MAUSER_SMG 1@exp 200 script fix_boy@fix_AnyStuff}
{309}{}{PID_223_PISTOL@Интеграция револьверного барабана в винтовку, да ещё и не того калибра - непростая задача, но в результат можно будет влюбиться. Для производства необходим верстак.@SK_REPAIR 60@SK_REPAIR 120&SK_SMALL_GUNS 80@PID_HUNTING_RIFLE 1&PID_44_MAGNUM_REVOLVER 1&PID_WELDING 1@PID_SUPER_TOOL_KIT 1@PID_223_PISTOL 1@exp 350 script fix_boy@fix_AnyStuff}
{400}{}{PID_FLAMER@Одним сварочным аппаратом совершаем магическое превращение груды металла в тело огнемёта, а вторым привариваем горелку и систему подачи топлива первого к этой конструкции.@SK_REPAIR 40@SK_REPAIR 60&SK_SCIENCE 40@PID_WELDING 2&PID_FLAMETHROWER_FUEL 5&PID_METAL_TRASH 2&PID_TUBE 1&PID_PUMP_PARTS 2@PID_SUPER_TOOL_KIT 1@PID_FLAMER 1@exp 200 }
{401}{}{PID_IMPROVED_FLAMETHROWER@Получив новый опыт в механике, вы поняли, что систему подачи топлива и сопло можно было бы переделать, чтобы уменьшить разбрызгивание топлива.@SK_REPAIR 100@SK_SCIENCE 70&SK_REPAIR 100&SK_BIG_GUNS 50@PID_PUMP_PARTS 2&PID_METAL_TRASH 1&PID_WELDING 1&PID_FLAMER 1&PID_FLAMETHROWER_FUEL 5@PID_SUPER_TOOL_KIT 1@PID_IMPROVED_FLAMETHROWER 1@exp 250 }
{500}{}{PID_LASER_PISTOL@Комбинация простого лазерного целеуказателя с хорошими конденсаторами и источником энергии может сделать его вполне реальным оружием.@SK_ENERGY_WEAPONS 50@SK_SCIENCE 80&SK_REPAIR 60&SK_ENERGY_WEAPONS 50@PID_SMALL_ENERGY_CELL 20&PID_METAL_TRASH 3&PID_PUMP_PARTS 2&PID_V15_COMPUTER_PART 3&PID_WELDING 1@PID_SUPER_TOOL_KIT 1&PID_BIG_BOOK_OF_SCIENCE 1@PID_LASER_PISTOL 1@exp 205 }
{501}{}{PID_MAGNETO_LASER_PISTOL@Установка специальных магнитов вокруг рубинового стержня уплотнит поток боевых фотонов.@SK_ENERGY_WEAPONS 50@SK_ENERGY_WEAPONS 50&SK_SCIENCE 100&SK_REPAIR 60@PID_LASER_PISTOL 1&PID_V15_COMPUTER_PART 5&PID_PUMP_PARTS 2@PID_SUPER_TOOL_KIT 1&PID_BIG_BOOK_OF_SCIENCE 1@PID_MAGNETO_LASER_PISTOL 1@exp 225 }
{502}{}{PID_LASER_RIFLE_EXT_CAP@После изучения технической литературы вы понимаете, что заводскую сборку можно очень сильно оптимизировать. Время поработать паяльником!@SK_ENERGY_WEAPONS 50@SK_REPAIR 90&SK_SCIENCE 130&SK_ENERGY_WEAPONS 60@PID_LASER_RIFLE 1&PID_V15_COMPUTER_PART 2&PID_PUMP_PARTS 2@PID_SUPER_TOOL_KIT 1&PID_BIG_BOOK_OF_SCIENCE 1@PID_LASER_RIFLE_EXT_CAP 1@exp 300 }
{503}{}{PID_PLASMA_PISTOL_EXT_CART@Отключить к чёрту системы охлаждения, и пистолет будет расходовать меньше энергии. Правда, стрелять придётся в перчатках.@SK_ENERGY_WEAPONS 50@SK_SCIENCE 110&SK_ENERGY_WEAPONS 60&SK_REPAIR 80@PID_PLASMA_PISTOL 1&PID_V15_COMPUTER_PART 2&PID_PUMP_PARTS 1@PID_SUPER_TOOL_KIT 1@PID_PLASMA_PISTOL_EXT_CART 1@exp 280 }
{504}{}{PID_TURBO_PLASMA_RIFLE@Вы бы никогда не поверили, что тепловая обмотка может ускорить формирование заряда, но так было написано в книжке. И вот он результат!@SK_SCIENCE 100&SK_ENERGY_WEAPONS 80@SK_SCIENCE 150&SK_ENERGY_WEAPONS 90&SK_REPAIR 120@PID_PLASMA_RIFLE 1&PID_WELDING 1&PID_V15_COMPUTER_PART 8&PID_PUMP_PARTS 3&PID_METAL_TRASH 3@PID_BIG_BOOK_OF_SCIENCE 1&PID_SUPER_TOOL_KIT 1@PID_TURBO_PLASMA_RIFLE 1@exp 350 }
{505}{}{PID_GATLING_LASER@Замените начинку "Авенджера" на боевую часть лазерной винтовки, а стволы заключите в обмотку из медной проволоки, сформировав на каждом электромагнит, который бы помогал фокусировать и уплотнять заряд.@SK_SCIENCE 100&SK_ENERGY_WEAPONS 80@SK_SCIENCE 110&SK_REPAIR 120&SK_ENERGY_WEAPONS 90@PID_AVENGER_MINIGUN 1&PID_LASER_RIFLE 1&PID_PUMP_PARTS 2&PID_V15_COMPUTER_PART 2@PID_SUPER_TOOL_KIT 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1@PID_GATLING_LASER 1@exp 400 }
{506}{}{PID_YK42B_PULSE_RIFLE@Сверхпроводящий ствол плазменной винтовки отлично подойдёт для того, чтобы собирать и направлять заряд с конденсаторов двух импульсных пистолетов, а система энергопитания от ядерных микрореакторов - для того, чтобы их запитать.@SK_SCIENCE 100&SK_ENERGY_WEAPONS 100@SK_SCIENCE 150&SK_ENERGY_WEAPONS 100&SK_REPAIR 120@PID_PLASMA_RIFLE 1&PID_YK32_PULSE_PISTOL 2&PID_METAL_TRASH 2&PID_V15_COMPUTER_PART 2&PID_MICRO_FUSION_CELL 10@PID_SUPER_TOOL_KIT 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1@PID_YK42B_PULSE_RIFLE 1@exp 500 }
{507}{}{PID_RAT_GRENADE_VENOM@Обработайте крысу токсином Хьюза и Лоуренса, пока она не очнулась.@@@PID_RAT_GRENADE 1&PID_SUPERTOXINE 1@@PID_RAT_GRENADE_VENOM 1@exp 150 script fix_boy@fix_VenomousRat}
{508}{}{PID_RAT_GRENADE_TNT@Это даже рецептом сложно назвать. Возьмите крысу, примотайте к ней скотчем динамит. Все.@@@PID_INSULATE_TAPE 1&PID_RAT_GRENADE 1&PID_DYNAMITE 1@@PID_RAT_GRENADE_TNT 1@script fix_boy@fix_TntRat}
{700}{}{PID_HEALING_POWDER@Разотрите камнем высушенные на солнце ингредиенты и заверните в тряпочку.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 30@PID_BROC_FLOWER 1&PID_XANDER_ROOT 1&PID_RAGS 1@PID_ROCK 1@PID_HEALING_POWDER 1@exp 50 }
{701}{}{PID_ANTIDOTE@Это будет скорей самовнушением. @SK_OUTDOORSMAN 30@SK_OUTDOORSMAN 40&SK_DOCTOR 20@PID_BOOZE 1&PID_SCORPION_TAIL 1@PID_LIGHTER 1@PID_ANTIDOTE 1@exp 90 }
{702}{}{PID_LOCKPICKS@Вы разбираетесь в этом деле и можете сами себе изготовить отмычки. В красивом кожаном чехле.@SK_LOCKPICK 20@SK_LOCKPICK 50&SK_REPAIR 30@PID_METAL_TRASH 1&PID_GECKO_PELT 1@PID_MULTI_TOOL 1@PID_LOCKPICKS 1@exp 10 }
{703}{}{PID_EXP_LOCKPICK_SET@Профессионалы вроде вас работают только с качественными инструментами!@SK_LOCKPICK 50@SK_LOCKPICK 80&SK_REPAIR 35@PID_LOCKPICKS 1&PID_METAL_TRASH 1&PID_PUMP_PARTS 1@PID_MULTI_TOOL 1@PID_EXP_LOCKPICK_SET 1@exp 150 }
{704}{}{PID_RADIO@Вам одиноко? Не с кем общаться? Вокруг одни сволочи и кротокрысы? Вам хочется об этом поговорить? Специально для вас! Схема простейшего приёмника в каждом номере "Электроники Дина"!@SK_SCIENCE 40@SK_SCIENCE 80&SK_REPAIR 50@PID_V15_COMPUTER_PART 1&PID_PUMP_PARTS 1&PID_METAL_TRASH 1@PID_MULTI_TOOL 1&PID_DEANS_ELECTRONICS 1@PID_RADIO 1@exp 120 }
{705}{}{PID_FIRST_AID_KIT@Бинты, спирт для промывки ран и другие полезные вещи в сумке из кожи многострадального гекко.@SK_FIRST_AID 50@SK_DOCTOR 50&SK_FIRST_AID 60&SK_SCIENCE 20@PID_RAGS 5&PID_BOOZE 1&PID_ANTIDOTE 1&PID_GECKO_PELT 1&PID_POCKET_LINT 1@@PID_FIRST_AID_KIT 1@exp 150 }
{706}{}{PID_RADIO@Почините радио с использованием деталей со старых микросхем.@SK_REPAIR 50@SK_REPAIR 60@PID_VIC_RADIO 1&PID_V15_COMPUTER_PART 1@PID_MULTI_TOOL 1@PID_RADIO 1@exp 100 }
{707}{}{PID_STIMPAK@Растворите целебный порошок в воде, наполните этой смесью стеклянный шприц и прокипятите. Потом простерилизуйте иглу спиртом.@SK_FIRST_AID 30@SK_FIRST_AID 80&SK_SCIENCE 80@PID_BOTTLE_FULL 1&PID_HYPODERMIC_NEEDLE 1&PID_BOOZE 1&PID_HEALING_POWDER 2@PID_LIGHTER 1&PID_CHEMISTRY_MANUAL 1&PID_FIRST_AID_KIT 1@PID_STIMPAK 1&PID_RAGS 1@exp 75 }
{708}{}{PID_SUPERTOXINE@Основной компонент яда - концентрированный токсин. Остальные ингридиенты легко найти в Пустоши.@@@PID_DANTON_POISON 1&PID_SCORPION_TAIL 1&PID_HYPODERMIC_NEEDLE 1@@PID_SUPERTOXINE 1@exp 200 script fix_boy@fix_SuperToxine}
{800}{}{PID_TNT@Вливайте азотную кислоту в толуол, постоянно нагревая. Получившийся осадок просушите. Готово.@SK_SCIENCE 60@SK_SCIENCE 100@PID_CHEMICALS 2&PID_BOTTLE_FULL 1@PID_LIGHTER 1&PID_CHEMISTRY_MANUAL 1@PID_TNT 3@exp 100 }
{801}{}{PID_FRAG_GRENADE@Поместите взрывчатое вещевство в осколочную рубашку и придумайте простенький взрыватель.@SK_REPAIR 80@SK_REPAIR 100@PID_PUMP_PARTS 1&PID_METAL_TRASH 1&PID_TNT 1@PID_MULTI_TOOL 1@PID_FRAG_GRENADE 1@exp 75 }
{802}{}{PID_PLASMA_GRENADE@Намотайте вокруг гранаты провод и подключите его к питанию, чтобы получился электромагнит. Выньте часть взрывчатого вещевства и изолируйте в образовавшемся пространстве небольшую полость. Автоматика поместит туда заряд плазмы.@SK_SCIENCE 80@SK_SCIENCE 80&SK_REPAIR 100@PID_PUMP_PARTS 1&PID_FRAG_GRENADE 1&PID_SMALL_ENERGY_CELL 1@PID_MULTI_TOOL 1@PID_PLASMA_GRENADE 1@exp 50 script fix_boy@fix_PlasmaGrenade}
{803}{}{PID_NITROGLYCERIN@Отделите жир от мяса, смешивайте с азотной и серной кислотой для получения нитроглицерина. Следите за тем, чтобы смесь не перегревалась во время реакции.@SK_SCIENCE 50@SK_SCIENCE 80&SK_OUTDOORSMAN 40@PID_MEAT 1&PID_CHEMICALS 2&PID_BOTTLE_FULL 1@PID_CHEMISTRY_MANUAL 1@PID_NITROGLYCERIN 5@exp 150 }
{804}{}{PID_DYNAMITE@Смешайте нитроглицерин с порошком для получения клейкой массы. Перемешайте её с опилками, скатайте в цилиндры и дайте высохнуть. Присоедините взрыватель.@SK_TRAPS 50@SK_OUTDOORSMAN 30&SK_TRAPS 80&SK_REPAIR 60@PID_NITROGLYCERIN 1&PID_HEALING_POWDER 1&PID_FIREWOOD 1&PID_V15_COMPUTER_PART 1&PID_PUMP_PARTS 1@PID_MULTI_TOOL 1&PID_DEANS_ELECTRONICS 1@PID_DYNAMITE 1@exp 200 }
{805}{}{PID_GUNPOWDER@Используйте кислоту для получения калийной селитры, смешайте 6 частей селитры с 1 частью угля и 1 серы.@SK_OUTDOORSMAN 40@SK_OUTDOORSMAN 50&SK_SCIENCE 80@PID_MINERAL 1&PID_CHEMICALS 1&PID_FIREWOOD 1@PID_CHEMISTRY_MANUAL 1&PID_ROCK 1@PID_GUNPOWDER 5@exp 100 }
{806}{}{PID_HEXOGEN@Получите нитрат аммония смешиванием собственной мочи с азотной кислотой и выпариванием. Добавьте толчёный буффаут. Залейте второй частью кислоты, охлаждайте, процедите осадок.@SK_SCIENCE 120@SK_SCIENCE 140&SK_OUTDOORSMAN 60@PID_BUFFOUT 1&PID_CHEMICALS 2&PID_BOTTLE_FULL 2&PID_RAGS 1@PID_LIGHTER 1&PID_CHEMISTRY_MANUAL 1@PID_HEXOGEN 3@exp 150 }
{807}{}{PID_PLASTIC_EXPLOSIVES_DULL@Найдите в мусоре какой-нибудь пластик, нагрейте его до плавления и вмешивайте в него порошок гексогена. Всё, теперь он удобен для хранения.@SK_SCIENCE 120@SK_OUTDOORSMAN 60&SK_REPAIR 60@PID_PUMP_PARTS 1&PID_HEXOGEN 1@PID_LIGHTER 1@PID_PLASTIC_EXPLOSIVES_DULL 1@exp 100 }
{808}{}{PID_PLASTIC_EXPLOSIVES@Соберите радиодетонатор из запчастей и старого радио.@SK_REPAIR 100@SK_REPAIR 130&SK_TRAPS 120@PID_PLASTIC_EXPLOSIVES_DULL 1&PID_PUMP_PARTS 1&PID_RADIO 1@PID_MULTI_TOOL 1&PID_DEANS_ELECTRONICS 1@PID_PLASTIC_EXPLOSIVES 1@exp 200 }
{809}{}{PID_MINE@Высыпьте гексоген в какую-нибудь старую банку, соорудите простенький взрыватель с использованием капсюля ружейного патрона.@SK_TRAPS 80@SK_TRAPS 130&SK_REPAIR 80&SK_OUTDOORSMAN 50@PID_HEXOGEN 1&PID_PUMP_PARTS 2&PID_SHOTGUN_SHELLS 1@PID_MULTI_TOOL 1@PID_MINE 1@exp 200 }
{900}{}{PID_RING_BOXING_GLOVES@Сшейте шкуры и набейте их мягким мусором.@SK_UNARMED 20@SK_UNARMED 50&SK_OUTDOORSMAN 40@PID_GECKO_PELT 2&PID_POCKET_LINT 4@PID_SHIV 1@PID_RING_BOXING_GLOVES 1@exp 150 }
{901}{}{PID_RING_PLATED_BOXING_GLOVES@Перчатки с утяжелителем - правильный выбор для участника подпольных боёв. Главное - не оставляйте их без присмотра в раздевалке, иначе грозит дисквалификация.@SK_UNARMED 40@SK_UNARMED 50&SK_OUTDOORSMAN 50&SK_REPAIR 30@PID_RING_BOXING_GLOVES 1&PID_METAL_TRASH 2@PID_MULTI_TOOL 1@PID_RING_PLATED_BOXING_GLOVES 1@exp 50 }
{902}{}{PID_BRASS_KNUCKLES@Пробейте дырки для пальцев в подходящей железяке, сможете попугать кого-нибудь. Только в драку с такой ерундой лучше не лезть.@SK_UNARMED 30@SK_UNARMED 50&SK_REPAIR 20@PID_METAL_TRASH 1@PID_MULTI_TOOL 1@PID_BRASS_KNUCKLES 1@exp 80 }
{903}{}{PID_SPIKED_KNUCKLES@Гуманизм - это для слабых. Не пожалейте денег на сварку, чтобы приварить шипы к своему старому кастету. Четыре дырки в противнике того стоят.@SK_UNARMED 30&SK_REPAIR 20@SK_UNARMED 50&SK_REPAIR 30@PID_BRASS_KNUCKLES 1&PID_METAL_TRASH 1@PID_WELDING 1@PID_SPIKED_KNUCKLES 1@exp 130 }
{904}{}{PID_CATTLE_PROD@Смонтируйте на дубинке простенький электрошокер, и жить станет веселей.@SK_REPAIR 40&SK_SCIENCE 40@SK_REPAIR 60&SK_SCIENCE 60@PID_CLUB 1&PID_PUMP_PARTS 2&PID_SMALL_ENERGY_CELL 10&PID_V15_COMPUTER_PART 2@PID_MULTI_TOOL 1@PID_CATTLE_PROD 1@exp 10 }
{905}{}{PID_SUPER_CATTLE_PROD@После изучения нужной литературы у вас появилась замечательная идея насчёт того, как можно увеличить мощность электрошокера, не испортив его.@SK_SCIENCE 60&SK_REPAIR 60@SK_SCIENCE 100&SK_REPAIR 80@PID_CATTLE_PROD 1&PID_V15_COMPUTER_PART 2&PID_PUMP_PARTS 2@PID_MULTI_TOOL 1&PID_DEANS_ELECTRONICS 1&PID_BIG_BOOK_OF_SCIENCE 1@PID_SUPER_CATTLE_PROD 1@exp 200 }
{906}{}{PID_SUPER_SLEDGE@Сварите из двух труб прочную рукоять, выточите на станке ударные части из железок попрочнее и оснастите их накопителем кинетической энергии согласно схеме. По сути, это просто жёсткая пружина и запирающий механизм.@SK_SCIENCE 80@SK_SCIENCE 100&SK_REPAIR 130@PID_METAL_TRASH 2&PID_PUMP_PARTS 1&PID_TUBE 2&PID_SMALL_ENERGY_CELL 5&PID_V15_COMPUTER_PART 1@PID_SUPER_TOOL_KIT 1@PID_SUPER_SLEDGE 1@exp 300 script fix_boy@fix_SuperSledge}
{907}{}{PID_WAKIZASHI_BLADE@Только человек, посвятивший себя изучению оружия, знает, как выковать настоящее лезвие.@SK_MELEE_WEAPONS 100@SK_MELEE_WEAPONS 130&SK_REPAIR 50&SK_OUTDOORSMAN 50@PID_FIREWOOD 1&PID_METAL_TRASH 3&PID_GECKO_PELT 1&PID_BOTTLE_FULL 3@PID_SLEDGEHAMMER 1&PID_LIGHTER 1@PID_WAKIZASHI_BLADE 1@exp 250 }
{908}{}{PID_COMBAT_KNIFE@Закалить заново лезвие, заточить, обмотать рукоять кожей, и этот нож уже можно называть оружием.@SK_MELEE_WEAPONS 40@SK_OUTDOORSMAN 20&SK_REPAIR 30&SK_MELEE_WEAPONS 50@PID_KNIFE 1&PID_GECKO_PELT 1&PID_FIREWOOD 1@PID_SLEDGEHAMMER 1@PID_COMBAT_KNIFE 1@exp 100 }
{909}{}{PID_SLEDGEHAMMER@Насадите железяку потяжелее на палку покрепче.@@SK_OUTDOORSMAN 30@PID_PUMP_PARTS 1&PID_FIREWOOD 1@@PID_SLEDGEHAMMER 1@exp 50 }
{910}{}{PID_SPEAR@Привяжите нож к палке. Это даст вам целый метр преимущества и килограмм уверенности.@@SK_OUTDOORSMAN 20&SK_MELEE_WEAPONS 40@PID_KNIFE 1&PID_ROPE 1&PID_SHARPENED_POLE 1@@PID_SPEAR 1@exp 80 }
{911}{}{PID_SHARP_SPEAR@Заточка копья кремнем от фирмы "Морлис" позволит разрубать врагов им как алебардой.@SK_OUTDOORSMAN 20@SK_MELEE_WEAPONS 40&SK_OUTDOORSMAN 30@PID_SPEAR 1&PID_FLINT 1@@PID_SHARP_SPEAR 1@exp 60 }
{912}{}{PID_SHARPENED_POLE@Вжик-вжик, готово!@@@PID_FIREWOOD 1@PID_KNIFE 1|PID_AXE 1|PID_COMBAT_KNIFE 1|PID_THROWING_KNIFE 1@PID_SHARPENED_POLE 1@exp 20 }
{913}{}{PID_CROWBAR@Нежными ударами придайте трубе правильную форму.@@SK_REPAIR 30@PID_TUBE 1@PID_SLEDGEHAMMER 1@PID_CROWBAR 1@exp 50 }
{914}{}{PID_WRENCH@Найдите железку подходящего размера и выпилите из неё нечто, чем можно было бы откручивать гайки.@@SK_REPAIR 30@PID_METAL_TRASH 1@PID_MULTI_TOOL 1@PID_WRENCH 1@exp 90 }
{915}{}{PID_KNIFE@Заточите несколько железяк, обмотайте рукояти какой-нибудь тряпкой. Получится несколько отличных ножей.@@SK_OUTDOORSMAN 20@PID_METAL_TRASH 1&PID_RAGS 1@@PID_KNIFE 3@exp 75 }
{916}{}{PID_CLUB@Отломайте нахрен минимум треть этой палки, забейте камнем в один конец какой-нибудь утяжелитель. Отломаный кусок можно притарабанить в качестве дополнительной рукояти. Готово, можно пойти проломить кому-нибудь черепушку.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 40&SK_REPAIR 30@PID_SHARPENED_POLE 1&PID_PUMP_PARTS 1@PID_ROCK 1@PID_CLUB 1@exp 60 }
{917}{}{PID_SHIV@Вырежьте из дерева рукоять, а потом забейте в неё железяку. Получилось шило, универсальный инструмент для проделывания дырок.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 30@PID_METAL_TRASH 1&PID_FIREWOOD 1@PID_KNIFE 1@PID_SHIV 1@exp 50 }
{918}{}{PID_THROWING_KNIFE@Сбалансируйте и дополнительно заточите эту железку.@SK_THROWING 40@SK_THROWING 50&SK_REPAIR 30@PID_KNIFE 1@PID_MULTI_TOOL 1@PID_THROWING_KNIFE 1@exp 70 }
{919}{}{PID_SHOVEL@Приладьте лопату к черенку и прибейте гвоздями.@@SK_OUTDOORSMAN 30@PID_METAL_TRASH 1&PID_SHARPENED_POLE 1@@PID_SHOVEL 1@exp 50 }
{920}{}{PID_AXE@Найдите какую-нибудь ветку, насадите на неё железяку поострее.@@SK_OUTDOORSMAN 30@PID_METAL_TRASH 1@@PID_AXE 1@exp 70 }
{921}{}{PID_SANDBAG_EMPTY@Сшейте мешок из кусков ткани.@@SK_OUTDOORSMAN 20@PID_RAGS 4&PID_POCKET_LINT 1@PID_SHIV 1@PID_SANDBAG_EMPTY 1@exp 60 }
{922}{}{PID_SANDBAG_1@Если наполнить этот мешок песком, получится... мешок с песком!@@@PID_SANDBAG_EMPTY 1@PID_SHOVEL 1@PID_SANDBAG_1 1@exp 10 }
{1000}{}{PID_ELEPHANT_GUN@Найдите токарный станок, используя его как сверлильный, рассверлите трубу до диаметра 17.8 мм, из куска металлического кола выточите затвор. По схемам из "Пушек и Пуль" изготовьте спусковой механизм, а приклад просто выточите из дерева.@SK_SCIENCE 40&SK_REPAIR 50@SK_SMALL_GUNS 80&SK_SCIENCE 60&SK_REPAIR 100@PID_TUBE 1&PID_PLANK 1&PID_FIREWOOD 1&PID_METAL_TRASH 4&PID_PUMP_PARTS 2@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_GUNS_AND_BULLETS 1@PID_ELEPHANT_GUN 1@exp 500 script fix_boy@fix_NitroExpress}
{1001}{}{PID_MULTI_BARREL_GUN@Несколько труб небольшого диаметра, распиленных на 19 одинаковых отрезков, и подведённые к каждому из них электрозапалы по схеме из "Пушек и пуль". Для производства необходим верстак.@SK_SCIENCE 60&SK_REPAIR 60@SK_SMALL_GUNS 80&SK_SCIENCE 100&SK_REPAIR 80@PID_TUBE 6&PID_FIREWOOD 2&PID_METAL_TRASH 4&PID_PUMP_PARTS 2&PID_SMALL_ENERGY_CELL 40&PID_V15_COMPUTER_PART 7@PID_WELDING 1&PID_GUNS_AND_BULLETS 1@PID_MULTI_BARREL_GUN 1@exp 350 script fix_boy@fix_AnyStuff}
{1002}{}{PID_METAL_STORM@Используйте 7 стволов от G11 для того, чтобы собрать самодельный пулемёт по схеме "Metalstorm", с продольным заряжанием безгильзовой аммуниции в ствол и активации её при помощи электрического запала. Придётся немного попаять. Для производства необходим верстак.@SK_SCIENCE 80&SK_REPAIR 80@SK_SMALL_GUNS 80&SK_SCIENCE 120&SK_REPAIR 100@PID_HK_G11E 7&PID_METAL_TRASH 8&PID_PUMP_PARTS 5&PID_MICRO_FUSION_CELL 50&PID_V15_COMPUTER_PART 15&PID_OIL_CAN 2@PID_SUPER_TOOL_KIT 1&PID_WELDING 2&PID_GUNS_AND_BULLETS 1@PID_METAL_STORM 1@exp 500 script fix_boy@fix_AnyStuff}
{1010}{}{PID_CHITIN_ARMOR@Разломать панцирь на мелкие куски. Осторожно помешивая, опустить в кипящие химикаты. 
На медленном огне варить смесь до растворения хитина и получения однородной массы.
Расплав слоями перенести на ткань, каждый слой ткани и расплава отформовать по фигуре.@@SK_REPAIR 110&SK_OUTDOORSMAN 100&ST_INTELLECT 6@PID_RADSCORPION_PARTS 8&PID_CHEMICALS 1&PID_RAGS 1&PID_METAL_TRASH 2&PID_LEATHER_ARMOR 1&PID_BOTTLE_FULL 1@PID_SUPER_TOOL_KIT 1@PID_CHITIN_ARMOR 1@exp 800 script fix_boy@fix_ChitinArmor}
